from pathlib import Path

p = Path('careerpilot/backend/main.py')
text = p.read_text(encoding='utf-8')
text = text.replace('from careerpilot.backend.agents.planner import PlannerState, build_planner_graph\n', 'import logging\nimport time\n\nfrom careerpilot.backend.agents.planner import PlannerState, build_planner_graph\n')
text = text.replace('settings = get_settings()\napp = FastAPI(title=settings.app_name)\nplanner_graph = build_planner_graph()\ncheckpoint_store = SQLiteCheckpointStore(settings.checkpoint_path)\nrag_service = get_rag_service()\n', 'settings = get_settings()\napp = FastAPI(title=settings.app_name)\nplanner_graph = build_planner_graph()\ncheckpoint_store = SQLiteCheckpointStore(settings.checkpoint_path)\nrag_service = get_rag_service()\nlogger = logging.getLogger("careerpilot")\n')
text = text.replace('    history = checkpoint_store.history(request.session_id, limit=settings.history_limit)\n    state: PlannerState = {\n        "user_query": request.message,\n        "session_id": request.session_id,\n        "history": history,\n        "metadata": {"focus": request.focus},\n    }\n    result = planner_graph.invoke(state)\n    payload = dict(result)\n    payload.setdefault("route", "fallback")\n    payload.setdefault("response", "")\n    payload.setdefault("metadata", {})\n    payload["metadata"] = {**payload.get("metadata", {}), "focus": request.focus}\n    checkpoint_store.save(session_id=request.session_id, step_name=payload.get("route", "fallback"), payload=payload)\n    return ChatResponse(\n        route=payload.get("route", "fallback"),\n        response=payload.get("response", ""),\n        session_id=request.session_id,\n        metadata=payload.get("metadata", {}),\n    )\n', '    query = request.message\n    if request.focus and request.focus != "all":\n        query = f"[{request.focus}] {query}"\n    history = checkpoint_store.history(request.session_id, limit=settings.history_limit)\n    started = time.perf_counter()\n    try:\n        result = planner_graph.invoke({\n            "user_query": query,\n            "session_id": request.session_id,\n            "history": history,\n            "metadata": {"focus": request.focus},\n        })\n        elapsed_ms = (time.perf_counter() - started) * 1000\n        metadata = dict(result.get("metadata") or {})\n        metadata["execution_time_ms"] = round(elapsed_ms, 1)\n        metadata["created_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())\n        checkpoint_store.save(\n            session_id=request.session_id,\n            step_name=result.get("route", "fallback"),\n            payload={\n                "user_query": query,\n                "route": result.get("route", "fallback"),\n                "response": result.get("response", ""),\n                "metadata": metadata,\n            },\n        )\n    except Exception as exc:\n        logger.exception("Chat request failed for session %s", request.session_id)\n        raise HTTPException(status_code=503, detail="CareerPilot is temporarily unavailable. Please try again.") from exc\n\n    payload = dict(result)\n    payload.setdefault("route", "fallback")\n    payload.setdefault("response", "")\n    payload.setdefault("metadata", {})\n    payload["metadata"] = {**payload.get("metadata", {}), "focus": request.focus}\n    payload["metadata"].update(metadata)\n    return ChatResponse(\n        route=payload.get("route", "fallback"),\n        response=payload.get("response", ""),\n        session_id=request.session_id,\n        metadata=payload.get("metadata", {}),\n    )\n')
p.write_text(text, encoding='utf-8')
print('updated main.py')
